before_script:
  - apt-get update -qy
  - apt-get install -y lftp

build:
  script:
    - lftp -v
    - lftp -e "set sftp:auto-confirm yes; open sftp://connect.bebroadband.co.za; user $FTP_USERNAME $FTP_PASSWORD; mirror -x .* -x .* / --reverse --verbose --delete .travis.yml /var/www/html/datatill/beBroadbandBackup/; bye"