langauge: minimal
env:
  global:
  - 'SFTP_USER=[root]'
  - 'SFTP_PASSWORD=[D@taTilLR0)t!@3]'
after_success:
- curl --ftp-create-dirs
       -T beBroadbandBackup
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@connect.bebroadband.co.za/var/www/html/datatill/beBroadbandBackup   
